language: java

jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: master
    app: user-management-finartz


notifications:
  email:
    recipients:
      - ahmetersxn@gmail.com
    on_success: always # default: change
    on_failure: never # default: always